[versions]
buildTools = "30.0.3"
compileSdk = "31"
targetSdk = "29"
minSdk = "24"

agp = "7.1.2"
kotlin = "1.6.0"

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
